### PR TITLE
Allow setting a custom adapter

### PR DESCRIPTION
**Pull request by Isigiel**
This will need a corresponding update on the contentful.js library but lays the groundwork for setting a custom adapter.
Such as [patrickhousley/ngx-axios-adapter](https://github.com/patrickhousley/ngx-axios-adapter) to allow the usa of the contenful sdk in an angular universal situation

### CODE REVIEW

**Comment by Isigiel** [comment]
Hey @Khaledgarbaya I'm no actually sure what you'd want to test there since it's just a config option passed to axios, but if you can line out what you'd want the tests to look like i'll give it a shot

**Comment by Isigiel** [comment]
Alright @Khaledgarbaya I added a test that should verify the new config option

**Comment by Isigiel** [comment]
@Khaledgarbaya Is this ready to merge then? WOuld be nice to get the functionality in soon

**Comment by Khaledgarbaya** [comment]
@Isigiel I am merging this now, do you want to update the contentful.js PR after this library is released

**Pull request merged**
